# Generated by Django 3.2.23 on 2024-01-26 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('watch_proj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watching_project', to='project.project'),
        ),
    ]
