from django.db import models
from django.contrib.auth.models import User


class WatchArtist(models.Model):
    """
    id generated by Big Auto.
    watching not to be confused with watched, in a familiar language:
    following not to be confused with followed
    """
    owner = models.ForeignKey(
        User, related_name='watching_artist', on_delete=models.CASCADE
    )
    watched = models.ForeignKey(
        User, related_name='account_watched', on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )

    class Meta:
        ordering = ['-created_at']
        unique_together = ['owner', 'watched']

    def __str__(self):
        return f'{self.owner} {self.watched}'
        