from django.db import models
from django.contrib.auth.models import User


class WatchArtist(models.Model):
    """
    id is automatically generated by Big Auto.
    related_name was 'following' and 'followed' in the tutorial.
    Reason watching is specified, is that there will be other "watching" apps.
    """
    owner = models.ForeignKey(
        User, related_name='watching_artist', on_delete=models.CASCADE
    )
    watched = models.ForeignKey(
        User, related_name='account_watched', on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )

    class Meta:
        ordering = ['-created_at']
        unique_together = ['owner', 'watched']
    
    def __str__(self):
        return f'{self.owner} {self.watched}'