# Generated by Django 3.2.23 on 2024-02-05 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paragitem',
            name='for_project',
        ),
        migrations.RemoveField(
            model_name='paragitem',
            name='owner',
        ),
        migrations.DeleteModel(
            name='ImageItem',
        ),
        migrations.DeleteModel(
            name='ParagItem',
        ),
    ]
