# Generated by Django 3.2.23 on 2024-02-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20240205_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deployed_link',
            field=models.URLField(blank=True),
        ),
    ]
