# Generated by Django 3.2.23 on 2024-02-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_deployed_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='feature_poster',
            field=models.ImageField(blank=True, default='../default_post_y8afhe', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_title',
            field=models.CharField(blank=True, default='untitled', max_length=50),
        ),
    ]
